Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numpy/compat/py3k.py", line 30, in <module>
    import pickle5 as pickle
ModuleNotFoundError: No module named 'pickle5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.compat._inspect import getargspec
  File "/usr/local/lib/python3.6/dist-packages/numpy/compat/__init__.py", line 14, in <module>
    from . import py3k
  File "/usr/local/lib/python3.6/dist-packages/numpy/compat/py3k.py", line 32, in <module>
    import pickle
  File "/usr/lib/python3.6/pickle.py", line 986, in <module>
    class _Unpickler:
  File "/usr/lib/python3.6/pickle.py", line 989, in _Unpickler
    encoding="ASCII", errors="strict"):
KeyboardInterrupt
Traceback (most recent call last):
  File "score.py", line 11, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/dist-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/multiarray.py", line 388, in <module>
    def lexsort(keys, axis=None):
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/overrides.py", line 209, in decorator
    docs_from_dispatcher=docs_from_dispatcher)(implementation)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/overrides.py", line 188, in decorator
    exec(source_object, scope)
  File "<__array_function__ internals>", line 2, in <module>
  File "/usr/lib/python3.6/functools.py", line 66, in update_wrapper
    for attr in updated:
KeyboardInterrupt
