2020-02-08 14:37:36.351678: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-08 14:37:36.367285: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ffdc7606190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-08 14:37:36.367321: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Using TensorFlow backend.
WARNING:tensorflow:Large dropout rate: 0.8 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
  File "train.py", line 368, in <module>
    run()
  File "train.py", line 198, in run
    df_from_each_file = [readCSV(f) for f in files[i:(i+arguments.fileBatchSize)]]
  File "train.py", line 198, in <listcomp>
    df_from_each_file = [readCSV(f) for f in files[i:(i+arguments.fileBatchSize)]]
  File "train.py", line 183, in readCSV
    return pd.read_csv(f, delimiter=',', engine='c', encoding="utf-8-sig")
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1094, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1134, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1180, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "/usr/local/lib/python3.7/site-packages/pandas/core/dtypes/common.py", line 811, in is_integer_dtype
    def is_integer_dtype(arr_or_dtype):
=================================================
        TRAINING v0.4.2 (binaryClasses)
=================================================
Date: 2020-02-08 14:37:36.347740
wrapLayerSize 2
coreLayerSize 4
numCoreLayers 1
outputLayerActivation sigmoid
output_dim 2
loss binary_crossentropy
optimizer sgd
[33m[INFO] using Sequential Dense layers[0m
[INFO] adding core layer 0
[INFO] created DNN
[33m[INFO] epoch 1/3[0m
[33m[INFO] loading file 1-2/1 on epoch 1/3[0m
[INFO] reading file data/SWaT2015-Attack-Files-v0.2/train/2015-12-28_113021_98.log.part12_sorted-labeled.csv
[EXCEPTION] (<class 'KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x14aaee820>)
--- 0.5233080387115479 seconds ---
